---
title: "Cabbages"
author: "Cienna Baker-Salgado"
date: "9/21/2024"
output:
  html_document:
    df_print: paged
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(MASS)
veggy <- cabbages
```

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->
 The cabbages data from the MASS package is loaded into a dataframe called veggy. Complete this report by answering the following two questions  
 
### Is there a difference in average VitC between c39 and c52 cultivation methods?

There is not a difference in VitC content between the cultivation of c39 and c52.

# Methods

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.!-->

Using the T test, we'll compare the means of both VitC groups. By examination of the variable cultivation you can explain the VitC numerical.

# Results

<!--Divide this section into two sub-sections:  One for your descriptive  results and one for your inferential results.!-->

## Descriptive Results

The c39 category for cabbage cultivation had a lower mean for the numerical VitC result, meanwhile the c52 category had a higher mean for the cultivation method.

### Graphical Descriptive Results

boxplot(VitC~Cult,data=veggy)

<!--Graphical results here.  Make sure to show your code.  Provide appropriate labels for axes, giving units if possible, and provide a good title for the graph, too.  Use the graphical results to describe the patterns if any that exist in the data as focused toward the research question!-->

### Numerical Descriptive Results

The cultivation method c39 has a median of 51.0 while c52 has a median of 64.5. C39 has a mean of 51.5 and c52 has a mean of 64.4. This means that the c52 method was more efficient in producing VitC.

favstats(VitC~Cult,data=veggy)

<!--Numerical results go here. Use the numerical results to describe the patterns if any that exist in the data as focused toward the research question!-->

## Inferential Results

Based on the sample tests, the p-value is 0.00000003405. Due to this it is possible to reject the null hypothesis because of the unlikely probability of the sample result.

t.test(VitC~Cult,data=veggy)

<!--State hypothesis clearly.  Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc.  Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->


# Discussion and Conclusion

Both cultivation methods, c39 and c52, have a numerical difference of VitC produced from the cabbage. The null hypothesis was rejected because of the results from the T test. C39 had the mean of 51.5 while c52 had the mean of 64.5 and our p-value was 0.00000003405. 

<!--Discussion and conclusion here.  If you found a relationship be sure to consider whether the relationship occurs because one of the variavbles causes the other, or whether they perhasps are related for some other reason.  Watch the chapter 6 videos from the GeorgeTown videos collection.!-->
